# 예외처리

>syntax Error :  문법에러 코딩상의 실수이므로 수정하지 않으면 프로그램이 동작하지 않음
>Runtime Error :  프로그램 작성 과정에서 논리상의 오류로 미처 대응하지 못한 상황이 발생하는 경우

## 1. try,catch
>try를 실행하는 도중 에러가 발생하면 catch(err) 블록으로 제어 흐름이 넘어감

>try에서 에러코드가 발생하지 않는 다면 try를 실행한후 catch블록은 건너뛴다.
```javascript
try {
    에러코드
    //에러코드 가
}catch {
    console.error(err.name);
}finally{
    console.log ('프로그램종료')
}
```
## 2. throw
>throw구문은 개발자 가 직접 에러를 발생시킬수 있는 구문(기능)이다.

>throw 구문은 그자체를 에러로 인식하기 때문에 try - catch 처리가 가능하다
```javascript
let  err = new Error('에러');

try {
    throw err;
}catch (err) {
    console.log ('에러이름 %s :',err.name);
    console.log ('에러내용 %s :',err.message);
}
//에러객체를 통한 예외처리
function a(x) {
    if (x == 1) {
        throw new Error('1은 입력할수 없는 숫자 입니다');
    } 
    return x;
}
let b = null;
try {
    b = a(1);
}catch (err) {
    console.log (err.message);
}
```

## 3. 사용자정의 에러
>에러클래스를 세분화하면 더욱 직관적으로 어느곳에서 에러가 났는지 확인가능하다.

>세분화 할때는 클래스의 상속 기능인 (extends)를 사용한다.

>상속하여 생성자를 만들때 부모클래스의 생성자를 변경하는 super(msg)기능을 사용하여 파라미터로 받은 메세지를 리턴할수 있게 해야한다.

>생성자에서 멤버변수 name을 바꿀때는 this.name 이라고 선언해도 되지만 super.name을 쓰는것이 좋아보인다
```javascript
class oddNum extends Error {
    constructor(msg) {
        //부모클래스의 생성자를 변경하는 기능 = super(msg)
        //부모 클래스의 생성자 내에 있는 이름을 변경하는 기능 = super.name
        super(msg);
        super.name = 'oddNum';
    }
}
class minNum extends Error {
    constructor(msg) {
        //부모클래스의 생성자를 변경하는 기능 = super(msg)
        //부모 클래스의 생성자 내에 있는 이름을 변경하는 기능 = super.name
        super(msg);
        super.name = 'minNum';
    }
}
function a(x) {
    if (x % 2 == 1) {
        throw new oddNum('홀수는 입력할수 없습니다');
    }
    if (x < 10) {
        throw new minNum('10보다 작은수는 입력 할수 없습니다.')
    } 
    return x;
}
let b = null;
try {
    b = a(1);
}catch (err) {
    console.log (err.message);
    console.log (err.name);
}
```
